;  Generated by PSoC Designer 5.4.3191
;
; =============================================================================
; FILENAME: PSoCConfigTBL.asm
;  
; Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
;  
; NOTES:
; Do not modify this file. It is generated by PSoC Designer each time the
; generate application function is run. The values of the parameters in this
; file can be modified by changing the values of the global parameters in the
; device editor.
;  
; =============================================================================
 
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_pdproject1_Bank1
export LoadConfigTBL_pdproject1_Bank0
export LoadConfigTBL_pdproject1_Ordered
AREA lit(rom, rel)
LoadConfigTBL_pdproject1_Bank0:
;  Instance name DUALADC_1, User Module DUALADC
;       Instance name DUALADC_1, Block Name ADC1(ASC10)
	db		80h, 90h		;DUALADC_1_bfADC1cr0(ASC10CR0)
	db		81h, 00h		;DUALADC_1_bfADC1cr1(ASC10CR1)
	db		82h, 61h		;DUALADC_1_bfADC1cr2(ASC10CR2)
	db		83h, f0h		;DUALADC_1_bfADC1cr3(ASC10CR3)
;       Instance name DUALADC_1, Block Name ADC2(ASD11)
	db		84h, 90h		;DUALADC_1_bfADC2cr0(ASD11CR0)
	db		85h, 00h		;DUALADC_1_bfADC2cr1(ASD11CR1)
	db		86h, 60h		;DUALADC_1_bfADC2cr2(ASD11CR2)
	db		87h, f0h		;DUALADC_1_bfADC2cr3(ASD11CR3)
;       Instance name DUALADC_1, Block Name CNT1(DBC00)
	db		23h, 00h		;DUALADC_1_bCounter1_CR0(DBC00CR0)
	db		21h, 00h		;DUALADC_1_bPeriod1(DBC00DR1)
	db		22h, 00h		;DUALADC_1_bCompare1(DBC00DR2)
;       Instance name DUALADC_1, Block Name CNT2(DCC03)
	db		2fh, 00h		;DUALADC_1_bCounter2_CR0(DCC03CR0)
	db		2dh, 00h		;DUALADC_1_bPeriod2(DCC03DR1)
	db		2eh, 00h		;DUALADC_1_bCompare2(DCC03DR2)
;       Instance name DUALADC_1, Block Name PWM16_LSB(DBC01)
	db		27h, 00h		;DUALADC_1_fPWM_LSB_CR0(DBC01CR0)
	db		25h, 00h		;DUALADC_1_bPWM_Period_LSB(DBC01DR1)
	db		26h, 00h		;DUALADC_1_bPWM_IntTime_LSB(DBC01DR2)
;       Instance name DUALADC_1, Block Name PWM16_MSB(DCC02)
	db		2bh, 00h		;DUALADC_1_fPWM_MSB_CR0(DCC02CR0)
	db		29h, 00h		;DUALADC_1_bPWM_Period_MSB(DCC02DR1)
	db		2ah, 00h		;DUALADC_1_bPWM_IntTime_MSB(DCC02DR2)
;  Instance name I2CHW_Temp, User Module I2CHW
;  Instance name LCD_2, User Module LCD
;  Instance name PGA_1, User Module PGA
;       Instance name PGA_1, Block Name GAIN(ACC00)
	db		71h, fdh		;PGA_1_GAIN_CR0(ACC00CR0)
	db		72h, a1h		;PGA_1_GAIN_CR1(ACC00CR1)
	db		73h, 20h		;PGA_1_GAIN_CR2(ACC00CR2)
	db		70h, 00h		;PGA_1_GAIN_CR3(ACC00CR3)
;  Instance name PGA_2, User Module PGA
;       Instance name PGA_2, Block Name GAIN(ACC01)
	db		75h, fdh		;PGA_2_GAIN_CR0(ACC01CR0)
	db		76h, a1h		;PGA_2_GAIN_CR1(ACC01CR1)
	db		77h, 20h		;PGA_2_GAIN_CR2(ACC01CR2)
	db		74h, 00h		;PGA_2_GAIN_CR3(ACC01CR3)
;  Instance name PWM8_1, User Module PWM8
;       Instance name PWM8_1, Block Name PWM8(DBC10)
	db		33h, 00h		;PWM8_1_CONTROL_REG(DBC10CR0)
	db		31h, ffh		;PWM8_1_PERIOD_REG(DBC10DR1)
	db		32h, 32h		;PWM8_1_COMPARE_REG(DBC10DR2)
;  Global Register values Bank 0
	db		62h, 00h		; AnalogClockSelect3 register (CLK_CR3)
	db		60h, 28h		; AnalogColumnInputSelect register (AMX_IN)
	db		66h, 00h		; AnalogComparatorControl1 register (CMP_CR1)
	db		61h, 00h		; AnalogMuxBusConfig register (AMUX_CFG)
	db		fch, 00h		; AnalogMuxDACData:0 register (IDACR_D)
	db		fdh, 00h		; AnalogMuxDACData:1 register (IDACL_D)
	db		63h, 15h		; AnalogReferenceControl register (ARF_CR)
	db		65h, 00h		; AnalogSynchronizationControl register (ASY_CR)
	db		e6h, 30h		; DecimatorControl_0 register (DEC_CR0)
	db		e7h, 00h		; DecimatorControl_1 register (DEC_CR1)
	db		a0h, 00h		; DecimatorDataHigh:0 register (DEC0_DH)
	db		a2h, 00h		; DecimatorDataHigh:1 register (DEC1_DH)
	db		a4h, 00h		; DecimatorDataHigh:2 register (DEC2_DH)
	db		a6h, 00h		; DecimatorDataHigh:3 register (DEC3_DH)
	db		a1h, 00h		; DecimatorDataLow:0 register (DEC0_DL)
	db		a3h, 00h		; DecimatorDataLow:1 register (DEC1_DL)
	db		a5h, 00h		; DecimatorDataLow:2 register (DEC2_DL)
	db		a7h, 00h		; DecimatorDataLow:3 register (DEC3_DL)
	db		d6h, 08h		; I2CConfig:0 register (I2C0_CFG)
	db		e8h, 00h		; Multiply0InputX register (MUL0_X)
	db		e9h, 00h		; Multiply0InputY register (MUL0_Y)
	db		a8h, 00h		; Multiply1InputX register (MUL1_X)
	db		a9h, 00h		; Multiply1InputY register (MUL1_Y)
	db		b7h, 00h		; RowDigitalInterconnectInputSelect:0 register (RDI0DSM)
	db		bfh, 00h		; RowDigitalInterconnectInputSelect:1 register (RDI1DSM)
	db		b0h, 00h		; Row_0_InputMux register (RDI0RI)
	db		b1h, 00h		; Row_0_InputSync register (RDI0SYN)
	db		b2h, 00h		; Row_0_LogicInputAMux register (RDI0IS)
	db		b3h, 33h		; Row_0_LogicSelect_0 register (RDI0LT0)
	db		b4h, 33h		; Row_0_LogicSelect_1 register (RDI0LT1)
	db		b5h, 00h		; Row_0_OutputDrive_0 register (RDI0RO0)
	db		b6h, 00h		; Row_0_OutputDrive_1 register (RDI0RO1)
	db		b8h, 55h		; Row_1_InputMux register (RDI1RI)
	db		b9h, 00h		; Row_1_InputSync register (RDI1SYN)
	db		bah, 10h		; Row_1_LogicInputAMux register (RDI1IS)
	db		bbh, 33h		; Row_1_LogicSelect_0 register (RDI1LT0)
	db		bch, 33h		; Row_1_LogicSelect_1 register (RDI1LT1)
	db		bdh, 08h		; Row_1_OutputDrive_0 register (RDI1RO0)
	db		beh, 00h		; Row_1_OutputDrive_1 register (RDI1RO1)
	db		ffh
LoadConfigTBL_pdproject1_Bank1:
;  Instance name DUALADC_1, User Module DUALADC
;       Instance name DUALADC_1, Block Name ADC1(ASC10)
;       Instance name DUALADC_1, Block Name ADC2(ASD11)
;       Instance name DUALADC_1, Block Name CNT1(DBC00)
	db		23h, 00h		;DUALADC_1_(DBC00CR1)
	db		20h, 21h		;DUALADC_1_fCounter1FN(DBC00FN)
	db		21h, 45h		;DUALADC_1_fCounter1SL(DBC00IN)
	db		22h, 40h		;DUALADC_1_fCounter1OS(DBC00OU)
;       Instance name DUALADC_1, Block Name CNT2(DCC03)
	db		2fh, 00h		;DUALADC_1_(DCC03CR1)
	db		2ch, 21h		;DUALADC_1_fCounter2FN(DCC03FN)
	db		2dh, 55h		;DUALADC_1_fCounter2SL(DCC03IN)
	db		2eh, 40h		;DUALADC_1_fCounter2OS(DCC03OU)
;       Instance name DUALADC_1, Block Name PWM16_LSB(DBC01)
	db		27h, 00h		;DUALADC_1_(DBC01CR1)
	db		24h, 01h		;DUALADC_1_bfPWM_LSB_FN(DBC01FN)
	db		25h, 15h		;DUALADC_1_(DBC01IN)
	db		26h, 40h		;DUALADC_1_(DBC01OU)
;       Instance name DUALADC_1, Block Name PWM16_MSB(DCC02)
	db		2bh, 00h		;DUALADC_1_(DCC02CR1)
	db		28h, 21h		;DUALADC_1_bfPWM_MSB_FN(DCC02FN)
	db		29h, 35h		;DUALADC_1_(DCC02IN)
	db		2ah, 40h		;DUALADC_1_(DCC02OU)
;  Instance name I2CHW_Temp, User Module I2CHW
;  Instance name LCD_2, User Module LCD
;  Instance name PGA_1, User Module PGA
;       Instance name PGA_1, Block Name GAIN(ACC00)
;  Instance name PGA_2, User Module PGA
;       Instance name PGA_2, Block Name GAIN(ACC01)
;  Instance name PWM8_1, User Module PWM8
;       Instance name PWM8_1, Block Name PWM8(DBC10)
	db		33h, 00h		;PWM8_1_(DBC10CR1)
	db		30h, 31h		;PWM8_1_FUNC_REG(DBC10FN)
	db		31h, 11h		;PWM8_1_INPUT_REG(DBC10IN)
	db		32h, 44h		;PWM8_1_OUTPUT_REG(DBC10OU)
;  Global Register values Bank 1
	db		61h, 00h		; AnalogClockSelect1 register (CLK_CR1)
	db		69h, 00h		; AnalogClockSelect2 register (CLK_CR2)
	db		8bh, 00h		; AnalogColumnClockDivide register (ACE_CLK_CR3)
	db		60h, 00h		; AnalogColumnClockSelect register (CLK_CR0)
	db		8ah, 00h		; AnalogEClockSelect1 register (ACE_CLK_CR1)
	db		89h, 00h		; AnalogEColumnClockSelect register (ACE_CLK_CR0)
	db		75h, 09h		; AnalogEColumnInputSelect register (ACE_AMX_IN)
	db		76h, 00h		; AnalogEComparatorControl0 register (ACE_CMP_CR0)
	db		77h, 00h		; AnalogEComparatorControl1 register (ACE_CMP_CR1)
	db		7ah, 33h		; AnalogELUTControl0 register (ACE_ALT_CR0)
	db		62h, 28h		; AnalogIOControl_0 register (ABF_CR0)
	db		67h, 33h		; AnalogLUTControl0 register (ALT_CR0)
	db		68h, 33h		; AnalogLUTControl1 register (ALT_CR1)
	db		63h, 00h		; AnalogModulatorControl_0 register (AMD_CR0)
	db		66h, 00h		; AnalogModulatorControl_1 register (AMD_CR1)
	db		6ah, 00h		; AnalogMuxBusConfig1 register (AMUX_CFG1)
	db		afh, 00h		; AnalogMuxClock register (AMUX_CLK)
	db		7bh, 00h		; AnalogOutBufferControl register (ACE_ABF_CR0)
	db		79h, 00h		; ComparatorGlobalInEn register (ACE_CMP_GI_EN)
	db		64h, 00h		; ComparatorGlobalOutEn register (CMP_GO_EN)
	db		65h, 00h		; ComparatorGlobalOutEn1 register (CMP_GO_EN1)
	db		fdh, 00h		; DAC_Control_0 register (IDAC_CR0)
	db		dch, 00h		; DAC_Control_1 register (IDAC_CR1)
	db		91h, 00h		; DEC_CR0:0 register (DEC0_CR0)
	db		95h, 00h		; DEC_CR0:1 register (DEC1_CR0)
	db		99h, 00h		; DEC_CR0:2 register (DEC2_CR0)
	db		9dh, 00h		; DEC_CR0:3 register (DEC3_CR0)
	db		9ah, 00h		; DecimatorControl_5 register (DEC_CR5)
	db		92h, 00h		; DecimatorEnable:0 register (DEC_CR3)
	db		96h, 00h		; DecimatorEnable:1 register (DEC_CR4)
	db		d4h, 00h		; Decimator_Control:0 register (DEC0_CR)
	db		d5h, 00h		; Decimator_Control:1 register (DEC1_CR)
	db		d6h, 00h		; Decimator_Control:2 register (DEC2_CR)
	db		d7h, 00h		; Decimator_Control:3 register (DEC3_CR)
	db		d1h, 00h		; GlobalDigitalInterconnect_Drive_Even_Input register (GDI_E_IN)
	db		a1h, 00h		; GlobalDigitalInterconnect_Drive_Even_Input_Control register (GDI_E_IN_CR)
	db		d3h, 00h		; GlobalDigitalInterconnect_Drive_Even_Output register (GDI_E_OU)
	db		a3h, 00h		; GlobalDigitalInterconnect_Drive_Even_Output_Control register (GDI_E_OU_CR)
	db		d0h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Input register (GDI_O_IN)
	db		a0h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Input_Control register (GDI_O_IN_CR)
	db		d2h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Output register (GDI_O_OU)
	db		a2h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Output_Control register (GDI_O_OU_CR)
	db		adh, 00h		; I2CAddress:0 register (I2C0_ADDR)
	db		e7h, 00h		; IDACMode register (IDACMODE)
	db		e1h, 19h		; OscillatorControl_1 register (OSC_CR1)
	db		e2h, 00h		; OscillatorControl_2 register (OSC_CR2)
	db		dfh, 95h		; OscillatorControl_3 register (OSC_CR3)
	db		deh, 02h		; OscillatorControl_4 register (OSC_CR4)
	db		ddh, 00h		; OscillatorGlobalBusEnableControl register (OSC_GO_EN)
	db		85h, 00h		; PWM_Control register (ACE_PWM_CR)
	db		d8h, 00h		; Port_0_MUXBusCtrl register (MUX_CR0)
	db		d9h, 00h		; Port_1_MUXBusCtrl register (MUX_CR1)
	db		dah, 00h		; Port_2_MUXBusCtrl register (MUX_CR2)
	db		dbh, 00h		; Port_3_MUXBusCtrl register (MUX_CR3)
	db		ech, 00h		; Port_4_MUXBusCtrl register (MUX_CR4)
	db		edh, 00h		; Port_5_MUXBusCtrl register (MUX_CR5)
	db		a7h, 00h		; RTClockControl register (RTCCR)
	db		a4h, 00h		; RTCurrentHour register (RTCH)
	db		a5h, 00h		; RTCurrentMinute register (RTCM)
	db		a6h, 00h		; RTCurrentSecond register (RTCS)
	db		82h, 00h		; TSCMPHigh register (SADC_TSCMPH)
	db		81h, 00h		; TSCMPLow register (SADC_TSCMPL)
	db		71h, 00h		; TSource0 register (SADC_TSCR0)
	db		72h, 00h		; TSource1 register (SADC_TSCR1)
	db		ffh
AREA psoc_config(rom, rel)
LoadConfigTBL_pdproject1_Ordered:
;  Ordered Global Register values
	M8C_SetBank0
	mov	reg[00h], 00h		; Port_0_Data register (PRT0DR)
	M8C_SetBank1
	mov	reg[00h], 00h		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], ffh		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[03h], ffh		; Port_0_DriveMode_2 register (PRT0DM2)
	mov	reg[02h], 00h		; Port_0_GlobalSelect register (PRT0GS)
	M8C_SetBank1
	mov	reg[02h], 00h		; Port_0_IntCtrl_0 register (PRT0IC0)
	mov	reg[03h], 00h		; Port_0_IntCtrl_1 register (PRT0IC1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	mov	reg[04h], a0h		; Port_1_Data register (PRT1DR)
	M8C_SetBank1
	mov	reg[04h], b0h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], eeh		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[07h], eeh		; Port_1_DriveMode_2 register (PRT1DM2)
	mov	reg[06h], 10h		; Port_1_GlobalSelect register (PRT1GS)
	M8C_SetBank1
	mov	reg[06h], 00h		; Port_1_IntCtrl_0 register (PRT1IC0)
	mov	reg[07h], 01h		; Port_1_IntCtrl_1 register (PRT1IC1)
	M8C_SetBank0
	mov	reg[05h], 01h		; Port_1_IntEn register (PRT1IE)
	mov	reg[08h], 00h		; Port_2_Data register (PRT2DR)
	M8C_SetBank1
	mov	reg[08h], 7fh		; Port_2_DriveMode_0 register (PRT2DM0)
	mov	reg[09h], 80h		; Port_2_DriveMode_1 register (PRT2DM1)
	M8C_SetBank0
	mov	reg[0bh], 80h		; Port_2_DriveMode_2 register (PRT2DM2)
	mov	reg[0ah], 00h		; Port_2_GlobalSelect register (PRT2GS)
	M8C_SetBank1
	mov	reg[0ah], 00h		; Port_2_IntCtrl_0 register (PRT2IC0)
	mov	reg[0bh], 00h		; Port_2_IntCtrl_1 register (PRT2IC1)
	M8C_SetBank0
	mov	reg[09h], 00h		; Port_2_IntEn register (PRT2IE)
	mov	reg[0ch], 00h		; Port_3_Data register (PRT3DR)
	M8C_SetBank1
	mov	reg[0ch], 00h		; Port_3_DriveMode_0 register (PRT3DM0)
	mov	reg[0dh], 00h		; Port_3_DriveMode_1 register (PRT3DM1)
	M8C_SetBank0
	mov	reg[0fh], 00h		; Port_3_DriveMode_2 register (PRT3DM2)
	mov	reg[0eh], 00h		; Port_3_GlobalSelect register (PRT3GS)
	M8C_SetBank1
	mov	reg[0eh], 00h		; Port_3_IntCtrl_0 register (PRT3IC0)
	mov	reg[0fh], 00h		; Port_3_IntCtrl_1 register (PRT3IC1)
	M8C_SetBank0
	mov	reg[0dh], 00h		; Port_3_IntEn register (PRT3IE)
	mov	reg[10h], 00h		; Port_4_Data register (PRT4DR)
	M8C_SetBank1
	mov	reg[10h], 00h		; Port_4_DriveMode_0 register (PRT4DM0)
	mov	reg[11h], 00h		; Port_4_DriveMode_1 register (PRT4DM1)
	M8C_SetBank0
	mov	reg[13h], 00h		; Port_4_DriveMode_2 register (PRT4DM2)
	mov	reg[12h], 00h		; Port_4_GlobalSelect register (PRT4GS)
	M8C_SetBank1
	mov	reg[12h], 00h		; Port_4_IntCtrl_0 register (PRT4IC0)
	mov	reg[13h], 00h		; Port_4_IntCtrl_1 register (PRT4IC1)
	M8C_SetBank0
	mov	reg[11h], 00h		; Port_4_IntEn register (PRT4IE)
	mov	reg[14h], 00h		; Port_5_Data register (PRT5DR)
	M8C_SetBank1
	mov	reg[14h], 00h		; Port_5_DriveMode_0 register (PRT5DM0)
	mov	reg[15h], 00h		; Port_5_DriveMode_1 register (PRT5DM1)
	M8C_SetBank0
	mov	reg[17h], 00h		; Port_5_DriveMode_2 register (PRT5DM2)
	mov	reg[16h], 00h		; Port_5_GlobalSelect register (PRT5GS)
	M8C_SetBank1
	mov	reg[16h], 00h		; Port_5_IntCtrl_0 register (PRT5IC0)
	mov	reg[17h], 00h		; Port_5_IntCtrl_1 register (PRT5IC1)
	M8C_SetBank0
	mov	reg[15h], 00h		; Port_5_IntEn register (PRT5IE)
	M8C_SetBank0
	ret


; PSoC Configuration file trailer PsocConfig.asm
