/******************************************************************************
*  Generated by PSoC Designer ???
******************************************************************************/
#include "DUALADC_1.h"
#include "LCD.h"
#include "LPF2_1.h"
#include "LPF2_2.h"
#include "PGA_1.h"
#include "PGA_2.h"
#include "PGA_3.h"
#include "PGA_4.h"
