/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// I2CHW_TempSDA address and mask defines
#pragma	ioport	I2CHW_TempSDA_Data_ADDR:	0x4
BYTE			I2CHW_TempSDA_Data_ADDR;
#pragma	ioport	I2CHW_TempSDA_DriveMode_0_ADDR:	0x104
BYTE			I2CHW_TempSDA_DriveMode_0_ADDR;
#pragma	ioport	I2CHW_TempSDA_DriveMode_1_ADDR:	0x105
BYTE			I2CHW_TempSDA_DriveMode_1_ADDR;
#pragma	ioport	I2CHW_TempSDA_DriveMode_2_ADDR:	0x7
BYTE			I2CHW_TempSDA_DriveMode_2_ADDR;
#pragma	ioport	I2CHW_TempSDA_GlobalSelect_ADDR:	0x6
BYTE			I2CHW_TempSDA_GlobalSelect_ADDR;
#pragma	ioport	I2CHW_TempSDA_IntCtrl_0_ADDR:	0x106
BYTE			I2CHW_TempSDA_IntCtrl_0_ADDR;
#pragma	ioport	I2CHW_TempSDA_IntCtrl_1_ADDR:	0x107
BYTE			I2CHW_TempSDA_IntCtrl_1_ADDR;
#pragma	ioport	I2CHW_TempSDA_IntEn_ADDR:	0x5
BYTE			I2CHW_TempSDA_IntEn_ADDR;
#define I2CHW_TempSDA_MASK 0x1
#pragma	ioport	I2CHW_TempSDA_MUXBusCtrl_ADDR:	0x1d9
BYTE			I2CHW_TempSDA_MUXBusCtrl_ADDR;
// I2CHW_TempSCL address and mask defines
#pragma	ioport	I2CHW_TempSCL_Data_ADDR:	0x4
BYTE			I2CHW_TempSCL_Data_ADDR;
#pragma	ioport	I2CHW_TempSCL_DriveMode_0_ADDR:	0x104
BYTE			I2CHW_TempSCL_DriveMode_0_ADDR;
#pragma	ioport	I2CHW_TempSCL_DriveMode_1_ADDR:	0x105
BYTE			I2CHW_TempSCL_DriveMode_1_ADDR;
#pragma	ioport	I2CHW_TempSCL_DriveMode_2_ADDR:	0x7
BYTE			I2CHW_TempSCL_DriveMode_2_ADDR;
#pragma	ioport	I2CHW_TempSCL_GlobalSelect_ADDR:	0x6
BYTE			I2CHW_TempSCL_GlobalSelect_ADDR;
#pragma	ioport	I2CHW_TempSCL_IntCtrl_0_ADDR:	0x106
BYTE			I2CHW_TempSCL_IntCtrl_0_ADDR;
#pragma	ioport	I2CHW_TempSCL_IntCtrl_1_ADDR:	0x107
BYTE			I2CHW_TempSCL_IntCtrl_1_ADDR;
#pragma	ioport	I2CHW_TempSCL_IntEn_ADDR:	0x5
BYTE			I2CHW_TempSCL_IntEn_ADDR;
#define I2CHW_TempSCL_MASK 0x2
#pragma	ioport	I2CHW_TempSCL_MUXBusCtrl_ADDR:	0x1d9
BYTE			I2CHW_TempSCL_MUXBusCtrl_ADDR;
